services:
  multi-agent:
    image: eladrab1106/multi-agent-app:latest
    container_name: multi-agent-app
    env_file:
      - .env
    stdin_open: true
    tty: true
    volumes:
      - ./credentials.json:/app/credentials.json
      - ./token.json:/app/token.json
      - ./outputs:/app/outputs
